# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-hle8eEjRhEE6b80vFRH7DWy5FgY8y3q
"""

pip install transformers torch gradio deep-translator

from transformers import AutoModelForCausalLM, AutoTokenizer
from deep_translator import GoogleTranslator
import torch
import gradio as gr

# Load chatbot model (offline)
tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-medium")
model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-medium")

# Store conversation history
chat_history_ids = None

# Supported languages
languages = {
    "English": "en",
    "Telugu": "te",
    "Hindi": "hi",
    "Tamil": "ta",
    "Kannada": "kn",
    "Malayalam": "ml"
}

def chat(user_input, selected_language):
    global chat_history_ids

    try:
        # Step 1: Translate user input to English
        english_input = GoogleTranslator(source='auto', target='en').translate(user_input)

        # Step 2: Generate response using DialoGPT
        input_ids = tokenizer.encode(english_input + tokenizer.eos_token, return_tensors='pt')
        if chat_history_ids is not None:
            bot_input_ids = torch.cat([chat_history_ids, input_ids], dim=-1)
        else:
            bot_input_ids = input_ids

        chat_history_ids = model.generate(bot_input_ids, max_length=1000, pad_token_id=tokenizer.eos_token_id)
        english_response = tokenizer.decode(chat_history_ids[:, bot_input_ids.shape[-1]:][0], skip_special_tokens=True)

        # Step 3: Translate response to selected language
        final_output = GoogleTranslator(source='en', target=languages[selected_language]).translate(english_response)
        return final_output

    except Exception as e:
        return f"⚠️ Error: {str(e)}"

# Gradio Interface
gr.Interface(
    fn=chat,
    inputs=[
        gr.Textbox(label="Ask your college-related question"),
        gr.Dropdown(choices=list(languages.keys()), value="English", label="Preferred Language")
    ],
    outputs="text",
    title="🎓 Offline Multilingual College Chatbot",
    description="Ask any college-related question in your language. No API needed!"
).launch()